version: "3"

services:
  expresskassa-server:
    build: .
    container_name: expresskassa-server
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      expresskassa-server-mysql:

  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    ports:
      - "8889:3306"
    networks:
      expresskassa-server-mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=expresskassa

networks:
  expresskassa-server-mysql: