jwt.secret: vlk3Tmn8$Xc49dC%hp3O#x6pghf

spring:
  datasource:
    url: jdbc:mysql://localhost:8889/express_kassa
    username: root
    password: root
  jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jpa.hibernate.ddl-auto: update
  jpa.show-sql: true
